package com.tts.TechTalentBlog.Domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

@Entity
public class BlogPost {
	
//	@Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "label_sequence")
//	@SequenceGenerator(name = "label_sequence", sequenceName = "label_sequence", allocationSize = 100)
//	private Long iid;
	

	// sets the Id as the Primary Key
	@Id
	/*
	 * 
TRUNCATE TABLE blog_post RESTART IDENTITY;
ALTER SEQUENCE blog_post_sequence RESTART WITH 1;
SELECT * FROM blog_post;
	 * 
	 */
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "blogPostSequence") //to be able to reset the id from 0 use SEQUENCE instead of AUTO .
	@SequenceGenerator(name = "blogPostSequence", sequenceName = "blogPostSequence", initialValue = 1)
	// allows the Id to be generated by the underlying database
//	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	public static Long count = 0L;

	private String title;
	private String author;
	private String blogEntry;

	public BlogPost() {
		// non-argument constructor needed for JPA
//		count++;
	}

	public BlogPost(String title, String author, String blogEntry) {
		this.title = title;
		this.author = author;
		this.blogEntry = blogEntry;
		count++;
	}

	public Long getId() {
		return id;
	}

	public void setCount() {
		count++;
	}

	public void setCount(int resetNum) {
		count = (long) resetNum;
	}

	public Long getCount() {
		return count;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getBlogEntry() {
		return blogEntry;
	}

	public void setBlogEntry(String blogEntry) {
		this.blogEntry = blogEntry;
	}

	@Override
	public String toString() {
		return "BlogPost [id=" + id + ", title=" + title + ", author=" + author + ", blogEntry=" + blogEntry + "]";
	}
}